language: node_js
node_js:
  - "stable"
  - 6

dist: trusty
sudo: false

services:
  - postgresql
  - redis-server

before_install:
  - psql -c 'create database fswd_test;' -U postgres

env:
  - SCRIPT=lint
  - SCRIPT=test

script: npm run $SCRIPT
